# Option
# https://goodgid.github.io/Spring-Boot-SQL-Option
# https://goodgid.github.io/Spring-Boot-SQL-Option-Show-SQL

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver-class-name}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정

# AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAVVFRUX2URBYKTXMH
      secretKey: 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
    s3:
      bucket: findu-i
    region:
      static: ap-northeast-2
    stack:
      auto: false